use payroll;
CREATE TABLE `registration` (
    `E_id` INT(20) UNSIGNED PRIMARY KEY NOT NULL AUTO_INCREMENT,
    `E_name` VARCHAR(30) DEFAULT NULL,
    `gender` VARCHAR(10) DEFAULT NULL,
    `E_DOB` VARCHAR(30) DEFAULT NULL,
    `E_email` VARCHAR(50) DEFAULT NULL,
    `Date_of_join` VARCHAR(20) DEFAULT NULL,
    `E_Dept` VARCHAR(20) DEFAULT NULL,
    `E_address` VARCHAR(50) DEFAULT NULL,
    `E_phno` VARCHAR(20) DEFAULT NULL,
    `Password` VARCHAR(30) DEFAULT NULL,
    `Confirm_Pass` VARCHAR(30) DEFAULT NULL
)  ENGINE=INNODB DEFAULT CHARSET=LATIN1;